
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os
from pathlib import Path

import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(os.getcwd() + '\\assets')


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def run_setup():
    subprocess.run(['python', 'setup.py'])

def run_main():
    user_input = entry_1.get()
    subprocess.run(['python', 'generate_graph.py', user_input])

window = Tk()

window.geometry("300x375")
window.configure(bg = "#010203")
window.title('Analisador de séries')

icon_path = os.getcwd() + '\\assets' + '\\window_icon.png'
window.iconphoto(True, PhotoImage(file=icon_path))


canvas = Canvas(
    window,
    bg = "#010203",
    height = 375,
    width = 300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    300.0,
    100.0,
    fill="#F5DE50",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    highlightthickness=0,
    borderwidth=0,
    bg="#010203",
    activebackground="#010203",
    command=run_main,
    relief="flat"
)
button_1.place(
    x=30.0,
    y=211.0,
    width=110.0,
    height=135.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    bg="#010203",
    activebackground="#010203",
    command=run_setup,
    relief="flat"
)
button_2.place(
    x=160.0,
    y=211.0,
    width=110.0,
    height=135.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    53.0,
    30.0,
    image=image_image_1
)

canvas.create_text(
    23.0,
    60.0,
    anchor="nw",
    text="ANALISADOR DE SÉRIES",
    fill="#000000",
    font=("SofiaSansRoman Regular", 21 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    150.0,
    167.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#CBCBCB",
    fg="#000716",
    highlightthickness=0,
    font=("Sophia Sans", 12)
)
entry_1.place(
    x=50.0,
    y=147.0,
    width=200.0,
    height=38.0
)

canvas.create_text(
    53.0,
    128.0,
    anchor="nw",
    text="NOME OU CÓDIGO DA SÉRIE",
    fill="#B59C1D",
    font=("SofiaSansRoman Regular", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
